# TODO: add customized author details (name, email)

name: Create Release
description: >-
  Creates a GitHub release including all commit
  messages from the inbound merge event.

  NOTE: This will ONLY work properly on a `push`
  event.

inputs:
  tag:
    description: >-
      Git tag to create the release from.
    required: true

  default_branch_name:
    description: >-
      The default Git branch for this repository.
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Get Formatted Commit Messages
      id: get-commit-messages
      shell: bash
      run: |
        # collect & format git commit messages
        msgs=$(git --no-pager log \
          --format="- [%an]: %s" \
          --ancestry-path ${{ github.event.before }}..${{ github.event.after }}
        )

        # produce the commit message output
        {
          echo "commit_messages<<EOF"
          echo "${msgs}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create-release
      shell: bash
      env:
        tag: ${{ inputs.tag }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create \
          "${tag}" \
          --notes '${{ steps.get-commit-messages.outputs.commit_messages }}' \
          "./make.psm1"
