
name: On Merge to Main

# TODO: on: pull_request
on:
  push:
    # only run this Workflow if the actual module
    # file or .VERSION file is touched
    paths:
      - make.psm1
      - .github/.VERSION

defaults:
  run:
    shell: bash

jobs:
  gate:
    name: Gate
    uses: ./.github/workflows/gate.yml

  create-tag:
    name: Create Tag
    needs: gate
    uses: ./.github/workflows/create-tag.yml
    with:
      tag: v${{ needs.gate.outputs.version }}
    permissions:
      contents: write

  create-release:
    name: Create Release
    needs: [gate, create-tag]
    uses: ./.github/workflows/create-release.yml
    with:
      tag: v${{ needs.gate.outputs.version }}
